AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: PetstoreAPI Sample
Globals:
  Function:
    Runtime: python3.7
    Environment:
      Variables:
        PETS_TABLE: !Ref PetsTable
    Layers:
      - !Ref PetStoreAPILayer
Resources:
  PetsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
  PetStoreAPILayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: 'Lambda Layer for Pet Store API'
      ContentUri: layer
  CreatePet:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create.handler
      CodeUri: src/handlers/pets
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PetsTable
  PetstoreAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: swagger.yaml
  LambdaPermissionCreatePet:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CreatePet
      Principal: apigateway.amazonaws.com
  CreatePetLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${CreatePet}
      RetentionInDays: 14
Outputs:
  ApiURL:
    Description: API endpoint URL for Petstore API
    Value: !Sub "https://${PetstoreAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
